POST http://localhost:9090/quests/admin
Accept: application/json
Content-Type: application/json

{
  "questName": "hello-world",
  "difficulty": "BEGINNER",
  "topic": "Basic syntax."
}

###

DELETE https://api.github.com/repos/bartmj/hello-world
Accept: application/vnd.github.v3+json
Authorization: Bearer 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