spring:
  jpa:
    open-in-view: false
    generate-ddl: true
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:file:./data/h2.db
  messages:
    basename: text
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 9090